version: "3.7"
services:
  db:
    build: ./db
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=rocks
      - DATABASE_HOST=localhost
    volumes:
      - "postgresdata:/data/db"
    ports:
      - 5432:5432
  api:
    build: ./api
    secrets:
      - DB_CONN
    environment:
      - DB_CONN_FILE=/run/secrets/DB_CONN
    depends_on:
      - db
    ports:
      - 5000:5000
    
  nextjs:
    build: ./nextjs
    depends_on:
      - db
    ports:
      - 3000:3000
secrets:
  DB_CONN:
    file: db_conn.txt
  POSTGRES_PASSWORD:
    file: postgres_password.txt
volumes:
  postgresdata:
