@hostname1=http://localhost:5000

# api server is on 5000, nextjs api is on 3000

GET {{hostname1}}/api/rocks/all

###

POST {{hostname1}}/api/rocks/create
Content-Type: application/json

{
    "name":"sandstone","texture":"rough","color":"tan"
}
###

PUT {{hostname1}}/api/rocks/1
Content-Type: application/json

{
    "name":"sandstone","texture":"smooth","color":"white"
}

###

DELETE {{hostname1}}/api/rocks/3

### nextjs api below

@hostname2=http://localhost:3000

# api server is on 5000, nextjs api is on 3000

GET {{hostname2}}/api/rocks

###

POST {{hostname2}}/api/rocks
Content-Type: application/json

{
    "name":"sandstone","texture":"rough","color":"tan"
}
###

PUT {{hostname2}}/api/rocks/1
Content-Type: application/json

{
    "name":"sandstone","texture":"smooth","color":"white"
}

###

DELETE {{hostname1}}/api/rocks/3